#!/bin/sh

#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

export NEDPATH=.:../lib:../../../src

MAKE="make MODE=debug"
EXEC_NAME="work_dbg"

if [ ! -d work ];  then mkdir work; fi

echo Copying test library lib/ to work/lib...
cp -a lib work/

opp_test gen -v *.test || exit 1
(cd work; opp_makemake -f --deep -lHaecComm_dbg -L../../src -P . --no-deep-includes -I../../src; $MAKE) || exit 1
opp_test run -v -p $EXEC_NAME *.test

echo Results can be found in ./work
